"""
Wrapper script for script generated by GNU Radio companion, in order to avoid
having to edit the autogenerated script directly.
"""

import evaluation_receiver
from datetime import datetime
import sys
import argparse
import time

parser = argparse.ArgumentParser()
# parser.add_argument('basename', type=str, help='Prefix for output filenames.')
# parser.add_argument('--center-freq', type=float, default=434000000)
# parser.add_argument('--samp-rate', type=float, default=20000)
# parser.add_argument('--gain', type=float, default=40)
parser.add_argument('--duration', type=float, default=20)
# parser.add_argument('--msg-interval', type=float, default=100)

args = parser.parse_args()

#generate base filename
output_filename_base = 'test_' + datetime.now().strftime('%Y-%m-%dT%M%S')

# print(output_filename_base)

#run grc flowgraph
#create and start flowgraph
flowgraph = evaluation_receiver.evaluation_receiver()

# flowgraph.set_gain(args.gain)
# flowgraph.set_freq(args.center_freq)
# flowgraph.set_samp_rate(args.samp_rate)

flowgraph.start()

time.sleep(args.duration)

flowgraph.stop()
flowgraph.wait()
